name: Manual Deployment with User Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      version:
        description: "Application Version (optional)"
        required: false
        default: "latest"
      dry_run:
        description: "Run as Dry Run?"
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Show User Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Dry Run: ${{ github.event.inputs.dry_run }}"

      - name: building Application
        if: github.event.inputs.dry_run == 'false'
        run: echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

  test:
    runs-on: ubuntu-latest
    environment: test
    needs: build
    steps:
      - name: Dev Show User Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Dry Run: ${{ github.event.inputs.dry_run }}"

      - name: testing Application
        if: github.event.inputs.dry_run == 'false'
        run: echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

  stage:
    runs-on: ubuntu-latest
    environment: stage
    needs: [build, test]
    steps:
      - name: stage Show User Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Dry Run: ${{ github.event.inputs.dry_run }}"

      - name: Deploy Application
        if: github.event.inputs.dry_run == 'false'
        run: echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"

  prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: stage
    steps:
      - name: stage Show User Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Dry Run: ${{ github.event.inputs.dry_run }}"

      - name: Deploy Application
        if: github.event.inputs.dry_run == 'false'
        run: echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}"
