name: Multi-Environment CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # 1️⃣ CI: Build, Lint, and Test
  ci:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4        
      - name: Build
        run: echo "building"
      - name: docker
        run: docker images
      - name: app path
        run: pwd

  # 2️⃣ Deploy to Development (Auto)
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: ci  # Ensures CI passes before deploying
    environment: dev  # Auto-deployment
    steps:
      - name: Deploy to Development
        run: echo "Deploying to Dev Environment"

  # 3️⃣ Deploy to QA (Auto after Dev)
  deploy-qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: qa  # Auto-deployment
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA Environment"

  # 4️⃣ Deploy to Staging (Manual Approval Required)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: deploy-qa
    environment: staging  # Requires manual approval
    timeout-minutes: 60  # Auto-fail if no approval within 60 minutes
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging Environment"

  # 5️⃣ Deploy to Production (Final Approval Required)
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production  # Requires manual approval
    timeout-minutes: 60
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production Environment"
